### ISSUE TITLE
links in docker-compose.yml not working

### ISSUE THREAD

**Issue by jl-** [heroku/heroku-docker#140]
Hey there. Does it support projects that have multi containers linking? Or maybe I'm doing something wrong. 
Here is my `docker-compose.yml`. I couldn't get things to work anyhow.

```yml
web:
  build: ./setup/nginx
  volumes:
    - ./setup/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./setup/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    - ./dist:/var/web/statics:ro
  ports:
    - '80:80'
  links:
    - app

app:
  build: .
  command: pm2 start web.json5 --no-daemon
  volumes:
    - .:/app/user:rw
  expose:
    - '9876'
  links:
    - redis

redis:
  build: ./setup/redis
  expose:
    - '6379'
```
`Dockerfile`s for `web`, `app`, `redis` may not be the cause of my problem, [Details](https://github.com/jl-/r-) can be found here.

`Procfile`: `web: nginx start`

It seems to me that `heroku docker:release --app=myherokuapp` not producing an slugs that linking other containers. Here is what I got when running the command:
```
Creating local slug...
Building web
Step 1 : FROM nginx:latest
 ---> 81415e35fc6c
Step 2 : MAINTAINER jl.z <i.dragonxx@gmail.com>
 ---> Running in 3ff1d94cee59
 ---> df44f6e6056b
Removing intermediate container 3ff1d94cee59
Step 3 : COPY ./nginx.conf /etc/nginx/
 ---> b79ee0682809
Removing intermediate container fbbd5b2f6952
Successfully built b79ee0682809
extracting slug from container...
creating remote slug...
language-pack: heroku-docker (nginx:latest)
remote process types: { web: 'cd /app/user && nginx start' }
uploading slug [====================] 100% of 0 MB, 0.0s                                                                                                 
releasing slug...
Successfully released xixi-web!
```
**The slug created seems to only using nginx Dockerfile, `app` and `redis` linkings were ignored**. 
If that's the limitation of this plugin for now, will there be any plans for supporting this?
