### ISSUE TITLE
How I made docker-compose work with the CLI

### ISSUE THREAD

**Issue by friism** [heroku/heroku-docker#25]
cc @hunterloftis 

I started with `ruby-getting-started` and this Ruby branch: https://github.com/heroku/heroku-docker/tree/improve-ruby-support

    heroku docker:init
    heroku docker:release 

The latter is to make sure an image gets generated. Create `docker-compose.yml`:

```
web:
  image: heroku-docker-caaf2273cbb5329ea01bd17b7f3ea8d0-start
  command: bundle exec puma -C config/puma.rb
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - DATABASE_URL=postgres://postgres@db:5432
    - RAILS_ENV=development
db:
  image: postgres
```

Note that you also have to go fuck with `config/database.yml`:

```
development:
  <<: *default

  #database: ruby-getting-started_development

  url: <%= ENV['DATABASE_URL'] %>
```

At this point, I can get my database going like this:

    docker-compose run web bundle exec rake db:migrate

Which seems pretty great.

And then I can visit my site running locally
